<?xml version="1.0" encoding="utf-8"?><Database Name="SistemaInformes" Class="DataEntitiesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=192.168.1.72;Initial Catalog=SistemaInformes;Persist Security Info=True;User ID=sa" SettingsObjectName="Entidades.Properties.Settings" SettingsPropertyName="SistemaInformesConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Asesores" Member="Asesores">
    <Type Name="Asesores">
      <Column Name="IdAsesor" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ApellidoPaterno" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ApellidoMaterno" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Correo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Usuario" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Contrasena" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Asesores_Usuarios" Member="Usuarios" ThisKey="IdAsesor" OtherKey="IdAsesor" Type="Usuarios" />
      <Association Name="Asesores_Predios" Member="Predios" ThisKey="IdAsesor" OtherKey="IdAsesor" Type="Predios" />
    </Type>
  </Table>
  <Table Name="dbo.Beneficiarios" Member="Beneficiarios">
    <Type Name="Beneficiarios">
      <Column Name="IdBeneficiario" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ApellidoPaterno" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ApellidoMaterno" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="IdPuesto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FechaRegistro" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="FechaEdicion" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaEliminado" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IdPredio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.String" DbType="NChar(12)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Informes" Member="Informes">
    <Type Name="Informes">
      <Column Name="IdInforme" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FechaCreacion" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Puestos" Member="Puestos">
    <Type Name="Puestos">
      <Column Name="IdPuesto" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="FechaRegistro" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="FechaEdicion" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaElimado" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IdRegistro" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Usuarios" Member="Usuarios">
    <Type Name="Usuarios">
      <Column Name="IdUsuario" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Contrasena" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="FechaRegistro" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaEdicion" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaEliminado" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IdAsesor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Asesores_Usuarios" Member="Asesores" ThisKey="IdAsesor" OtherKey="IdAsesor" Type="Asesores" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Municipios" Member="Municipios">
    <Type Name="Municipios">
      <Column Name="IdMunicipio" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdEstado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Localidades" Member="Localidades">
    <Type Name="Localidades">
      <Column Name="IdLocalidad" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdMunicipio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Estados" Member="Estados">
    <Type Name="Estados">
      <Column Name="IdEstado" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Predios" Member="Predios">
    <Type Name="Predios">
      <Column Name="IdPredio" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Superficie" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IdAsesor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdEstado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdMunicipio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdLocalidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FechaRegistro" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="FechaEliminado" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaEdicion" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="Asesores_Predios" Member="Asesores" ThisKey="IdAsesor" OtherKey="IdAsesor" Type="Asesores" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Apoyos" Member="Apoyos">
    <Type Name="Apoyos">
      <Column Name="IdApoyo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FechaRegistro" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FechaEdicion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaEliminado" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Programa" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Anio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>