//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaInformes.Configuraciones {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class SettingsDocuments : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsDocuments defaultInstance = ((SettingsDocuments)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsDocuments())));
        
        public static SettingsDocuments Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PathReportes {
            get {
                return ((string)(this["PathReportes"]));
            }
            set {
                this["PathReportes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PathInfornes {
            get {
                return ((string)(this["PathInfornes"]));
            }
            set {
                this["PathInfornes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PathNominas {
            get {
                return ((string)(this["PathNominas"]));
            }
            set {
                this["PathNominas"] = value;
            }
        }
    }
}
