//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaInformes.Configuraciones {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class SettingsPrinter : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsPrinter defaultInstance = ((SettingsPrinter)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsPrinter())));
        
        public static SettingsPrinter Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NamePrinter {
            get {
                return ((string)(this["NamePrinter"]));
            }
            set {
                this["NamePrinter"] = value;
            }
        }
    }
}
